# Generated by Django 3.2.9 on 2021-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211119_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite_products',
            field=models.BooleanField(default=False),
        ),
    ]
